services:
  infra-workshop:
    image: utkusarioglu/tf-devcontainer:23-ubuntu-test-23
    environment:
      TZ: Etc/UTC0
      CLUSTER_HOSTNAME: infra-workshop.utkusarioglu.com

      HOST_ROOT: $PWD

      K3D_NODE_VOLUME_ROOT: /dev/xvdf
      K3D_HOST_VOLUME_RELPATH: artifacts/volumes

      MODULES_RELPATH: src/modules
      CONFIG_RELPATH: src/config
      TARGETS_RELPATH: src/targets

      KUBE_ARTIFACTS_RELPATH: artifacts/kube
      TERRAGRUNT_DOWNLOAD_DIR_RELPATH: artifacts/terragrunt-cache
    
      HOSTS_ENTRIES_START_PHRASE: '# HOSTS LIST START'
      HOSTS_ENTRIES_END_PHRASE: '# HOSTS LIST END'
      HOST_GATEWAY_PHRASE: host-gateway

    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu/infra-workshop
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

      - type: bind
        source: /home/utkusarioglu/.kube
        target: /home/dev/.kube
      - type: bind
        source: ~/.aws/credentials
        target: /home/dev/.aws/credentials
        read_only: true

    extra_hosts:
      host-gateway: host-gateway
