services:
  infra-workshop:
    image: utkusarioglu/tf-devcontainer:23-ubuntu-test-21
    environment:
      TZ: Etc/UTC0
      CLUSTER_HOST: local.dev.k3d.infra-workshop.utkusarioglu.com
      CLUSTER_REGION: eu-central-1

      HOST_ROOT: $PWD
      NODE_VOLUME_ROOT: /dev/xvdf
      HOST_VOLUME_RELPATH: artifacts/volumes
      TERRAGRUNT_DOWNLOAD_DIR: artifacts/cache
      MODULES_RELPATH: src/modules
      CONFIG_RELPATH: src/config
      TARGETS_RELPATH: src/targets
      ARTIFACTS_RELPATH: artifacts

    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu/infra-workshop
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /home/utkusarioglu/.kube
        target: /home/dev/.kube
    extra_hosts:
      host-gateway: host-gateway
    