apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wp-mariadb-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path

parameters:
  nodePath: ${default_volume_path}
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: Immediate
reclaimPolicy: Delete
